server:
  port: 8888

---
# datasource
spring:
  datasource:
    url: jdbc:mysql://58.87.87.4:3306/spring-cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root-hetongxue
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# druid
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false

---
# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.hetongxue.cloud.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: assign_id

---
# jpa
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: mysql

---
# 日志
logging:
  level:
    root: info
    com.hetongxue.cloud.mapper: debug

---
# 其他
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true